//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm_tbl
    {
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage="Backend validation: first name required")]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string TrainingLocation { get; set; }
        public Nullable<bool> Math { get; set; }
        public Nullable<bool> Physics { get; set; }
        public Nullable<bool> Chemistry { get; set; }
        public int id { get; set; }
    }
}
